export const GATE_SUBJECTS = [
  { name: 'Engineering Mathematics', slug: 'engg-math', icon: '∑', color: 'blue' },
  { name: 'Digital Logic', slug: 'digital-logic', icon: '⊕', color: 'purple' },
  { name: 'Computer Organization & Architecture', slug: 'coa', icon: '⚙', color: 'orange' },
  { name: 'Programming & Data Structures', slug: 'pds', icon: '{ }', color: 'green' },
  { name: 'Algorithms', slug: 'algorithms', icon: 'O(n)', color: 'red' },
  { name: 'Theory of Computation', slug: 'toc', icon: 'λ', color: 'indigo' },
  { name: 'Compiler Design', slug: 'compiler', icon: '⟹', color: 'pink' },
  { name: 'Operating Systems', slug: 'os', icon: '🖥', color: 'teal' },
  { name: 'Databases', slug: 'dbms', icon: '⊗', color: 'yellow' },
  { name: 'Computer Networks', slug: 'cn', icon: '⇄', color: 'cyan' },
  { name: 'General Aptitude', slug: 'aptitude', icon: '◆', color: 'emerald' },
  { name: 'Verbal Ability', slug: 'verbal', icon: 'Aa', color: 'rose' },
] as const

export const SUBJECT_COLORS: Record<string, string> = {
  blue: 'bg-blue-500',
  purple: 'bg-purple-500',
  orange: 'bg-orange-500',
  green: 'bg-green-500',
  red: 'bg-red-500',
  indigo: 'bg-indigo-500',
  pink: 'bg-pink-500',
  teal: 'bg-teal-500',
  yellow: 'bg-yellow-500',
  cyan: 'bg-cyan-500',
  emerald: 'bg-emerald-500',
  rose: 'bg-rose-500',
}

export const SUBJECT_TEXT_COLORS: Record<string, string> = {
  blue: 'text-blue-600 dark:text-blue-400',
  purple: 'text-purple-600 dark:text-purple-400',
  orange: 'text-orange-600 dark:text-orange-400',
  green: 'text-green-600 dark:text-green-400',
  red: 'text-red-600 dark:text-red-400',
  indigo: 'text-indigo-600 dark:text-indigo-400',
  pink: 'text-pink-600 dark:text-pink-400',
  teal: 'text-teal-600 dark:text-teal-400',
  yellow: 'text-yellow-600 dark:text-yellow-400',
  cyan: 'text-cyan-600 dark:text-cyan-400',
  emerald: 'text-emerald-600 dark:text-emerald-400',
  rose: 'text-rose-600 dark:text-rose-400',
}

export const SUBJECT_BG_COLORS: Record<string, string> = {
  blue: 'bg-blue-50 dark:bg-blue-950/30',
  purple: 'bg-purple-50 dark:bg-purple-950/30',
  orange: 'bg-orange-50 dark:bg-orange-950/30',
  green: 'bg-green-50 dark:bg-green-950/30',
  red: 'bg-red-50 dark:bg-red-950/30',
  indigo: 'bg-indigo-50 dark:bg-indigo-950/30',
  pink: 'bg-pink-50 dark:bg-pink-950/30',
  teal: 'bg-teal-50 dark:bg-teal-950/30',
  yellow: 'bg-yellow-50 dark:bg-yellow-950/30',
  cyan: 'bg-cyan-50 dark:bg-cyan-950/30',
  emerald: 'bg-emerald-50 dark:bg-emerald-950/30',
  rose: 'bg-rose-50 dark:bg-rose-950/30',
}

export const GATE_SYLLABUS: Record<string, string[]> = {
  'engg-math': [
    'Discrete Mathematics',
    'Linear Algebra',
    'Calculus',
    'Probability & Statistics',
    'Mathematical Logic',
    'Set Theory & Algebra',
    'Combinatorics',
    'Graph Theory',
    'Numerical Methods',
  ],
  'digital-logic': [
    'Boolean Algebra',
    'Combinational Circuits',
    'Sequential Circuits',
    'Number Systems',
    'Minimization Techniques',
    'Flip-Flops & Latches',
    'Counters & Registers',
    'Memory & PLDs',
  ],
  'coa': [
    'Machine Instructions & Addressing',
    'ALU Design',
    'Control Unit',
    'Pipelining',
    'Memory Hierarchy',
    'Cache Memory',
    'Virtual Memory',
    'I/O Interface',
    'Instruction Level Parallelism',
  ],
  'pds': [
    'Programming in C',
    'Recursion',
    'Arrays & Strings',
    'Linked Lists',
    'Stacks & Queues',
    'Trees & BST',
    'Heaps',
    'Hashing',
    'Graphs',
  ],
  'algorithms': [
    'Asymptotic Analysis',
    'Recurrences',
    'Sorting Algorithms',
    'Searching',
    'Divide & Conquer',
    'Greedy Algorithms',
    'Dynamic Programming',
    'Graph Algorithms',
    'NP-Completeness',
  ],
  'toc': [
    'Regular Languages & FA',
    'Regular Expressions',
    'Context-Free Languages',
    'Push-Down Automata',
    'Turing Machines',
    'Decidability',
    'Complexity Classes',
    'Pumping Lemma',
  ],
  'compiler': [
    'Lexical Analysis',
    'Syntax Analysis',
    'Parsing Techniques',
    'Semantic Analysis',
    'Intermediate Code',
    'Code Optimization',
    'Code Generation',
    'Symbol Tables',
  ],
  'os': [
    'Process Management',
    'CPU Scheduling',
    'Synchronization',
    'Deadlocks',
    'Memory Management',
    'Virtual Memory',
    'File Systems',
    'I/O Systems',
    'Protection & Security',
  ],
  'dbms': [
    'ER Model',
    'Relational Model',
    'SQL',
    'Normalization',
    'Transaction Management',
    'Concurrency Control',
    'Recovery',
    'Indexing',
    'Query Optimization',
  ],
  'cn': [
    'OSI & TCP/IP Model',
    'Data Link Layer',
    'Network Layer',
    'Routing Algorithms',
    'Transport Layer',
    'Application Layer',
    'Network Security',
    'Switching',
    'Congestion Control',
  ],
  'aptitude': [
    'Numerical Ability',
    'Percentage & Ratio',
    'Logical Reasoning',
    'Analytical Reasoning',
    'Data Interpretation',
    'Problem Solving',
    'Spatial Reasoning',
  ],
  'verbal': [
    'English Grammar',
    'Vocabulary',
    'Reading Comprehension',
    'Sentence Completion',
    'Critical Reasoning',
    'Para Jumbles',
  ],
}
